name: Build

on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Test build environment
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PATH
        shell: C:/msys64/msys2_shell.cmd -no-start -defterm {0}
