name: Build

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Test build environment
    runs-on: windows-latest
    steps:
      - run: |
          choco uninstall mingw
          C:/msys64/msys2_shell.cmd -no-start -defterm -c 'echo $PATH'
          cmd /S /C '"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat" && C:/msys64/msys2_shell.cmd -no-start -defterm -c "echo $PATH"'
