name: Build

on:
  push:
    branches: [master]
    
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
  b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
  c:
    runs-on: ubuntu-latest
    needs: ${{ matrix.needs }}
    strategy:
      matrix:
        needs: [a, b]
