name: Build

on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Test build environment
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'coin-or/coinbrew'
      - run: |
          "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat" 
          bash -c "./coinbrew build Cbc@latest --enable-msvc --no-prompt --build=x86_64-w64-mingw32"
        shell: cmd