name: Build

on:
  push:
    branches: [master]
    
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test build environment
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          powershell ./scripts/msys2 'echo $PATH'
